name: NyaaUtils
main: cat.nyaa.nyaautils.NyaaUtils
description: "Plugin for Nyaacat Minecraft Server"
version: 1.0
depend: [Vault]
softdepend: [LockettePro]
authors: [RecursiveG]
website: "https://github.com/NyaaCat/nyaautils"
database: false

commands:
  nyaautils:
    description: The command for NyaaUtils
    aliases: nu
    permission: nu.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  nu.command:
    description: Base permission node for commands
    default: true
  nu.enchant:
    description: Permission node for self-serve enchanting
    default: true
  nu.show:
    description: Permission node for show item
    default: true
  nu.reload:
    description: Reload permission
    default: op
  nu.addenchsrc:
    description: Add item as enchantment source
    default: op
  nu.launch:
    description: Launch player into sky
    default: op
  nu.lootprotect:
    description: Toggle loot protect status
    default: true
  nu.exhibition.set:
    description: Exhibition modification
    default: true
  nu.exhibition.unset:
    description: Exhibition modification
    default: true
  nu.exhibition.desc:
    description: Exhibition modification
    default: true
  nu.exhibition.forceUnset:
    description: Exhibition modification
    default: op
  nu.prefix:
    default: true
  nu.suffix:
    default: true
  nu.format:
    default: true
  nu.project:
    description: Set player velocity
    default: op
  nu.mailbox:
    description: Basic permission requied for mailbox
    default: true
  nu.mailadmin:
    description: Administrative commands for mailbox
    default: op
